### ISSUE TITLE
Sign up view

### ISSUE THREAD

**Issue by tatankayotanka** [SNDjango/server#1]
As a user, I want to click the Sign up button so that I see the Sign up form

Acceptance Сriteria:

- Clicking the Sign Up button on main view logged out redirects to sign up view
- Sign up view displays Input fields: user name, e-mail and password, all of them should be marked as required
- Input field user name should take the value up to 32 symbols and have corresponding hint
- E-mail input field should have the hint with e-mail address format
- Password field should be not shorter than 8 symbols and have corresponding hint
- Sign up view displays Buttons: sign up and cancel
- Clicking the cancel button redirects to Main view logged out
- Sign Up button is implemented in a separate story

**Comment by atamankina** [comment]
Here is an example of input hints: https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_input_help-block&stacked=h

**Comment by uttamdhakal** [comment]
When I leave username blank and click the signup button it redirects me to the "ValueError at /signup" page. Shouldn't it simply show me the error message?

**Comment by ericaivarsson** [comment]
I agree with Uttam, This should be put in acceptance criteria. Or well, it´s kind of in acceptance criteria already with the fact that it should be "required". but definitely, the error should be within the page so that the user can quickly correct the error without having to type the other details again (minus maybe password which he might have to re-type).

**Comment by atamankina** [comment]
[UX Spec.pdf](https://github.com/SNDjango/server/files/1032010/UX.Spec.pdf)

**Comment by atamankina** [comment]
@uttamdhakal, @ericaivarsson input validation and error handling is a part of https://github.com/SNDjango/server/issues/29

**Comment by atamankina** [comment]
Verified with Firefox 53.0.3 on Windows 8.1 on devel branch with latest commit e82ae04

Issue reported:
improvement https://github.com/SNDjango/server/issues/54

**Comment by atamankina** [comment]
Re-opened as acceptance criteria not met:
Sign up view displays Buttons: sign up and cancel
Clicking the cancel button redirects to Main view logged out

**Comment by atamankina** [comment]
Verified with Google Chrome on Windows 8.1, devel branch,  latest commit 392225a.
