### ISSUE TITLE
Content item visual representation

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#11]
As a user, I want to see content and related actions grouped together so that I can see possible interactions with the content

Acceptance criteria:
- Content item layout as defined in UX spec
- Content information like title, author, description, publication date relate to that specific content item
- Following buttons are displayed with each content item: Add to Favorites, Add Comment, Share
- Actions on Action buttons will be implemented in separated stories

**Comment by ericaivarsson** [comment]
Does anyone know how this works with the database? When a picture is uploaded, should we have an attribute already for it which is "# likes" , which at upload will be default 0, but anytime someone likes a picture, the value for "# likes" will be updated in database? 

How do we store comments? Are they stored in the database with the picture itself, or maybe in a table for comments which connects to the picture with foreign key? 

While we are on this topic, we also have to consider how we do with the "favourites" -> how do we save information on that? I guess one idea would be to have e.g. for me, i have pressed 3 pictures as "as favorite" and then in the database I  wil have Favorite 1, favorite 2, favorite 3, each of them linked with a foreign key to the picture it is about? 

I might be lost here, please help if you got more insight :) I guess we might need to open a separate ticket for this or?

**Comment by pr0me** [comment]
I would suggest to have a look at Django's own comment framework.
I guess it will be suitable for us :)

https://docs.djangoproject.com/en/1.7/ref/contrib/comments/

**Comment by BenKet** [comment]
Index page shows all posts from the Database
myPost shows all posts from logged in user

A post contains:
- title
- description
- Image (test link right now, but easy to change if picture upload works)
- author
- timestamp
- buttons (like, comments, share, add to favoite => buttons without function)

Problems: 
- myfavorite page shows no posts yet. It is necessary to change the data structure. Do we want to do this in the next sprint?

**Comment by BenKet** [comment]
Ah okay just saw the comment

**Comment by atamankina** [comment]
Verified with Google Chrome on Windows 8.1, devel branch, latest commit 4098113 .
