### ISSUE TITLE
Page about rules

### ISSUE THREAD

**Issue by ericaivarsson** [SNDjango/server#115]
As a user, I want to be informed about what rules I should adhere to when I publish posts on the website and I want to be informed about some (basic) stuff concerning TUGag.

Acceptance criteria:

- A static page with the rules clearly expressed : 

- Treat others with respect

- No pornography

- No  violence, gory and harmful content

- No  illegal activities
Source and inspiration: https://about.9gag.com/the-9gag-rules-f99fdc965b85

**Comment by uttamdhakal** [comment]
We already have FAQ Page, can't we list rules there? Is this page even necessary?

**Comment by BenKet** [comment]
I can do that, it can be a part of the footer links, like imprint...

**Comment by ericaivarsson** [comment]
http://127.0.0.1:8000/rules  - Verified on Firefox 54.0 and Safari 9.1.2 on Macbook Air 10.11.6. 
As previously mentioned, this will become a dynamic page in a later sprint under a new ticket.
