### ISSUE TITLE
Rest API to create user

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#120]
As a developer of integrated system, I want to have a Rest API to create a user so that I can:
- send a request with necessary input
- get a success response
- get a fail response.

**Comment by ericaivarsson** [comment]
@atamankina  - I´m having a problem with the logic of this one - should we not create a password for the new user so that we can use that to login with the new user details? (= make password mandatory as well). Otherwise we will have created a user that we can never login?

**Comment by atamankina** [comment]
@ericaivarsson fix merged, password is now required
