### ISSUE TITLE
Rest API to update user

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#121]
As a developer of integrated system, I want to have a Rest API to update a user so that I can:
- send a request with necessary input
- get a success response
- get a fail response.

**Comment by ericaivarsson** [comment]
@atamankina where is the code so that I can review this?

**Comment by ericaivarsson** [comment]
Verified with Postman according to our wiki.

Test case 1:   
- changed username of my superuser in Postman. 
- tried to login on our webpage with my old username - did not work. (Message: User does not exist) logged in with the changed username = success. 
- used the REST_API to change my username back to original again.  

Test case 2: 
- changed first name and last name in Postman. 
- went to my profile on our webpage: my names were updated accordingly.
