### ISSUE TITLE
Rest API to get user details

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#122]
As a developer of integrated system, I want to have a Rest API to get user details so that I can:
- send a request with necessary input
- get a success response
- get a fail response.

**Comment by ericaivarsson** [comment]
Für was brauchen wir diesem ticket? Ich habe der Situation nicht gut verstanden (create user , und update user, ja, aber diesem verstehe ich nicht ) @atamankina

**Comment by atamankina** [comment]
@ericaivarsson sometimes we just want to view user's details :) like send a request and get user's profile as response, this task should handle it.

**Comment by ericaivarsson** [comment]
Verified with Postman according to our wiki.
