### ISSUE TITLE
Rest API to list users

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#123]
As a developer of integrated system, I want to have a Rest API to list users so that I can:
- send a request with necessary input
- get a success response
- get a fail response.

**Comment by atamankina** [comment]
![postman](https://user-images.githubusercontent.com/28013464/27660132-556c764a-5c56-11e7-8f05-1316f43a84e7.png)

**Comment by ericaivarsson** [comment]
@atamankina I am a bit confused, should I review this only based on the screenshot?

**Comment by ericaivarsson** [comment]
I´m not sure if this belongs to here, but im getting the following warning when running server: 

?: (urls.W005) URL namespace 'rest_framework' isn't unique. You may not be able to reverse all URLs in this namespace

**Comment by henryk3dp** [comment]
it complains about two urlpatterns using the same namespace, the rest_framework and the router one. it's not an issue now.

**Comment by ericaivarsson** [comment]
Verified with Postman according to our wiki.
