### ISSUE TITLE
Display content on main page

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#13]
As a user, I want to see the already existing content on the main page so that I can view it and have fun

Acceptance criteria:
- Existing content is displayed as a list of content items
- The list is sorted by publication date, recent first

Implementation question:
- How difficult is it to implement dynamic content loading? In case we have 1000 items, fetching and rendering them can take a very long time, so we should limit the number of displayed items
- We can start with the limitation: show the first 10 items and add a button "Show 10 more"

**Comment by henryk3dp** [comment]
We could use react to load data asynchronously. we can do that after implementing the REST API, so maybe in the second sprint.

**Comment by atamankina** [comment]
Let's start with showing the first 10 items. Added a spike to investigate further: https://github.com/SNDjango/server/issues/28

**Comment by ericaivarsson** [comment]
Maybe on main page we can do the "last 10 items that are uploaded". 

But if we want to create a "hot" page, then one idea could be to implement "get stream" if we want to do a shortcut: https://getstream.io  
Installation of stream on django here: https://github.com/GetStream/stream-django 

Example here of "trending" stream page here: (Of a "pinterest"type social media: http://exampledjango.getstream.io/) 
Code of this example page here: https://github.com/GetStream/Stream-Example-Py 

Also other things can be done with Stream. Try their API here: https://getstream.io/get_started/#flat_feed

**Comment by henryk3dp** [comment]
we rather need infinite scroll than a newsfeed type of functionality i believe. something like django endless pagination. 
Edit: or simply use jquery to implement it, we already have it as a dependency through bootstrap.

**Comment by henryk3dp** [comment]
also, free software only, please. things that depend on a cloud service are out of the question.

**Comment by atamankina** [comment]
@pr0me Please, do not show the default text like "You will be able to explore fun memes below" in case there is content, it should be there only if there is nothing else to show.

**Comment by atamankina** [comment]
Verified with Google Chrome on Windows 8.1, devel branch, latest commit 4098113 .
