### ISSUE TITLE
Comment task 2--As a user, I want to see comments on posts

### ISSUE THREAD

**Issue by tatankayotanka** [SNDjango/server#137]
When comments exist
1. Use can see the most recent 2 comments below the ContentItem
2. There is a button view all comments, see all comments OR alternative --> there is a button "load more comments", and can load e.g. 2-5 comments at the time.

**Comment by ericaivarsson** [comment]
I would say "see all comments" it´s not a great idea if the post has 1000 comments, then the user will be presented with an ocean of comments straight away. Instead I would suggest we implement a "load mroe comments" similarly to like we have "load more posts" on our index page. And thus we load a definite amount of comments each time the user clicks on the button, e.g. 5 comments at a time or so. Facebook uses also this technology, and instragram too.  

Obviously there should be a statement like IF more comments are available -> then view button, if not, don´t view the button. It would be annoying for the user to see the button "load more comments" if there is no more comments to show. If difficult, then this can become a improvement later on and we leave the button there always if takes too much effort to do the if statement.

**Comment by tatankayotanka** [comment]
@ericaivarsson For this sprint, the goal is to display comments. Any improvement goes into the next Sprint.

**Comment by ericaivarsson** [comment]
I´ve tested it, it works fine.
