### ISSUE TITLE
Comment task 3 Spike--As a user, I want to upvote or downvote a comment

### ISSUE THREAD

**Issue by tatankayotanka** [SNDjango/server#138]
When comments exist
1. Each comment is displayed with two buttons, thumb up and thumb down
2. Click on thumb up, the count is incremented by 1, click on thumb down, the count is incremeted by 1

**Comment by ericaivarsson** [comment]
Where should we place the replies? Straight under the message that is being replied  to e.g. like Facebook currently? Or simply in the order in the comments list based on date of publication of the comment? (Like Youtube had for a long time)?

**Comment by tatankayotanka** [comment]
@ericaivarsson This ticket is defined as a spike. Now the idea is upvote and downvote a comment. There is huge complication when we want to display replies to a comment, a replies to a reply. I will change the requirements to the ticket.

**Comment by ericaivarsson** [comment]
@tatankayotanka I´d like to review this, but i can´t find the corresponding branch?
