### ISSUE TITLE
Improve Sort algorithm

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#141]
As is user I want to have a sort algorithm, so that i have some pictures in hot, top and new.

**Comment by ericaivarsson** [comment]
How do we separate hot from top? is top the "all time top" (only considering amount of likes) while "hot" is a mixture of the time stamp + amount of likes? (so that hot will only be recent items while top can be very old items?

**Comment by atamankina** [comment]
Verified. Issues won't fix.
