### ISSUE TITLE
Footer

### ISSUE THREAD

**Issue by BenKet** [SNDjango/server#142]
As a user I want to see a footer where I can find the informations about the Imprint and contact Informations.

**Comment by ericaivarsson** [comment]
I´d suggest we put the Rules and FAQ there too.

**Comment by ericaivarsson** [comment]
@BenKet are you doing this or not? When not I can take it :) If yes: Pleeaaase assign yourself to the ticket!!

**Comment by ericaivarsson** [comment]
does this ticket include generating the content for imprint and contact informations or is it solely the footer with the links? If the latter, we will need tickets for imprint and contact informations too.  

@BenKet  Please define acceptance criteria. (otherwise QA don´t know what to test against)

**Comment by BenKet** [comment]
OKay I'm sorry, yeah I will do it :) 
and yes I can creat a Imprint page and so on

**Comment by ericaivarsson** [comment]
Verified with Firefox 54.0 and Chrome 59.0.3071.115 on Mac OS 10.11.6.
