### ISSUE TITLE
Adjust data model to add boards

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#143]
Make a modell for boards. Consider the required connections:
- board includes posts
- board created by user
- board subscribed by users (be able to retrieve 1) List of users + 2) a number of the total amount of subscribed users?) 
- date (timestamp) of creaton of board

**Comment by ericaivarsson** [comment]
@atamankina is this only an adjustment to a model (i.e. dokumentation) or to the actual database?

**Comment by tatankayotanka** [comment]
ContentBoard is used as a bridge model for Content and Board, resolving issue "Board includes posts"
admin is a User that creates the board
Timestamp not implemented and not essential for this sprint.
SubBoard model bridges subscribers and board

Any further improvements should be added as tickets for the next sprint

Summary: board model exists for creating boards

**Comment by atamankina** [comment]
Verified.
