### ISSUE TITLE
Add button to subscribe/unsubscribe for boards

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#146]
As a user, I want to be able to subscribe for interesting boards

- Each listed board has a subscribe button
- Successful subscribing shows a success message
- The subscribe button turns to unsubscribe after subscribing
- Successful unsubscribing shows a success message
- The unsubscribe button turns to subscribe after unsubscribing

**Comment by ericaivarsson** [comment]
@atamankina Really nice AC!!

**Comment by ericaivarsson** [comment]
Verified with Firefox 54.0 & Safari 9.1.2 on Mac OS 10.11.6. 
All according to AC, apart from no (written) message when subscribing/unsubscribing. not necessary however, as the UX is good enough to understand it with the colouring of the heart in red/grey. top!
