### ISSUE TITLE
Add page for viewing my subscribed boards

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#147]
As a user, I want to see all my subscribed boards in one page

- Navigation menu item
- Page shows only my boards

**Comment by ericaivarsson** [comment]
I would suggest that when the user clicks on his little profile icon at the navigation bar, a dropdown list appears with the following options as for now "profile", "boards". (then more things can be added as we add more functionality regarding the user. ("such as "settings" where the user later can delete his account).
