### ISSUE TITLE
Like Comments function

### ISSUE THREAD

**Issue by jkaschner** [SNDjango/server#168]
As a user I want to like a comment with a button (like thumbs-up) and be able to unlike it again. Similar functionality to liking a post. 

Acceptance criteria: 

- When I press on the like button, the number increments with 1 

- When I press again on the button, it reduces with 1 ("unlike") 
- There should be a count in the database how much likes a comment has, in order to make a sort function based on most likes.

**Comment by ericaivarsson** [comment]
Verified with Firefox 54.0 & Safari 9.1.2 on Mac OS 10.11.6.
