### ISSUE TITLE
Click Login button to sign in

### ISSUE THREAD

**Issue by tatankayotanka** [SNDjango/server#2]
As a registered user, I want to click on the Login button after filling in Sign In form  so that I can sign in and start using the website

Acceptance Criteria:
- clicking the Login button starts checking the input fields
- if input is valid, the user is redirected to main page
- if input is invalid, no redirect occurs and the user sees the corresponding error message

Error cases:
- invalid user name: invalid username message
- invalid password: invalid password message

Implementation questions:
error message can be inline or another page depending on required effort

**Comment by ericaivarsson** [comment]
For me it seems like this item has already been worked on. Who did it? Can you please put yourself as "assignee"? I have moved it to "in progress" but in my opinion this story has already been completed and should be put in ready for review. The person who made the code for this in html and python, can you please update the status of this story and leave your comment that could help us understand what is missing?

**Comment by ericaivarsson** [comment]
I will review this as soon as I can. (hopefully thursday)

**Comment by tatankayotanka** [comment]
Present status : invalid input(s) results triggers off error message "invalid login, please try again" with the login form directly below to enable another login.

**Comment by ericaivarsson** [comment]
The current status does not comply with the acceptance criteria. The acceptance criteria says there should be different messages depending on what the error is (password-related or username related). 
How should we proceed? Should we fix this issue now or in a later story?

**Comment by henryk3dp** [comment]
you need to pull an up-to-date version. behaviour matches acceptance criteria.

**Comment by atamankina** [comment]
Verified with Firefox 53.0.3 on Windows 8.1 on devel branch with latest commit e82ae04
