### ISSUE TITLE
Upload Image

### ISSUE THREAD

**Issue by pr0me** [SNDjango/server#20]
As a user, I want to upload a new image, describe it (using hashtags) and set its visibility.

Acceptance Criteria:
- The "Select file" button opens file selection window
- The accepted formats are .jpg, .png, .gif
- File size should be limited to 5 MB (or suggest meaningful limitation)
- The upload page contains the following Input fields: Title (max 100 chars), Description (max 500 chars), 
- Hashtags (have proper hashtag format) - another story
- The "Submit" button starts input validation: image format and size, and format for hashtags
- If validation is passed, the content object is created in the database and the user sees the success message
- If validation is not passed, the user sees corresponding error message

Error cases:
- File format wrong
- File size wrong
- Hashtag format wrong - another story

**Comment by atamankina** [comment]
The story needs to be broken down as it covers several functional parts. AC need to be specified.

**Comment by ericaivarsson** [comment]
Here is some help: http://www.bogotobogo.com/python/Django/Python_Django_Image_Files_Uploading_Example.php

**Comment by ericaivarsson** [comment]
here some more info: (simple file upload) https://simpleisbetterthancomplex.com/tutorial/2016/08/01/how-to-upload-files-with-django.html

**Comment by atamankina** [comment]
Image preview and Drag and drop for file upload can/should be implemented in another story

**Comment by atamankina** [comment]
[UX Spec.pdf](https://github.com/SNDjango/server/files/1032010/UX.Spec.pdf)

**Comment by henryk3dp** [comment]
Hashtags will be implemented after the corresponding models are done (issue #35).
Drag and drop functionality will be added at a later point. needs ajax or something similar, because browsers block setting the value of an input file field using javascript for security reasons.

**Comment by ericaivarsson** [comment]
I get "Could not write to Database" when trying to upload image - anyone know why?

**Comment by henryk3dp** [comment]
@ericaivarsson make sure you applied all migrations.

**Comment by atamankina** [comment]
Verified with Firefox 53.0.3 on Windows 8.1 on devel branch with latest commit e82ae04

Reported issues:
critical: handle gracefully clicking upload if no file selected https://github.com/SNDjango/server/issues/62
improvements:
https://github.com/SNDjango/server/issues/63
https://github.com/SNDjango/server/issues/64
https://github.com/SNDjango/server/issues/65
https://github.com/SNDjango/server/issues/66
https://github.com/SNDjango/server/issues/67
