### ISSUE TITLE
Create tasks for Search Images

### ISSUE THREAD

**Issue by pr0me** [SNDjango/server#21]
As a user or guest, I want to search the images, using categories/hashtags.

**Comment by atamankina** [comment]
The story needs to be broken down as it covers several functional parts. AC need to be specified.

**Comment by ericaivarsson** [comment]
This ticket is in theory not "ready" as @atamankina has already said, it is missing acceptance criteria. 

I´m a bit confused by the tickets with the names "create tasks for.."  - what do we mean by this?

**Comment by ericaivarsson** [comment]
@BenKet  if you are already working on this one please assign yourself to the ticket!

**Comment by ericaivarsson** [comment]
Useful info from page 112: https://books.google.de/books?id=Xs_2CQAAQBAJ&pg=PA119&lpg=PA119&dq=django+search+for+hashtags&source=bl&ots=tKAYM-bpfF&sig=rFQp08LZOsH9aryrqbjErxma7Ic&hl=en&sa=X&ved=0ahUKEwi92MjjlMjUAhWCXRoKHWUYBFgQ6AEIXDAJ#v=onepage&q=django%20search%20for%20hashtags&f=false

**Comment by BenKet** [comment]
As a user or guest, I want to search the Memes, by hashtags. 

- I want to enter a hashtag and I want to see the Memes of that Hashtag
- I want to get the memes orderd by date and "Hotness"
