### ISSUE TITLE
Main view logged in

### ISSUE THREAD

**Issue by jkaschner** [SNDjango/server#3]
As a user, I want to see the main page after I login.

Acceptance criteria:
- Navbar is visible on the top of the page
- App name navbar item is active, other items are inactive
- Empty room is displayed: "Here you will see the web site content as soon as it arrives."

**Comment by ericaivarsson** [comment]
I can review this tomorrow

**Comment by ericaivarsson** [comment]
Have reviewed. It´s complying with Acceptance criteria.

**Comment by atamankina** [comment]
Verified with Firefox 53.0.3 on Windows 8.1 on devel branch with latest commit e82ae04.
