### ISSUE TITLE
FAQ Page

### ISSUE THREAD

**Issue by ericaivarsson** [SNDjango/server#30]
As a user, I want to be informed about different questions I may have that other users have already asked, and thus I can look them up in FAQ instead of contacting TU-Gag. 

Acceptance criteria: 
- relevant questions and useful and understandable answers
- information about the way the site works/categories etc. ("Getting started")
- information about profile ("Settings")
- Visible in Navbar or alternative in footer in the bottom on the page.

**Comment by atamankina** [comment]
Verified.
