### ISSUE TITLE
Code and Commit guidelines

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#34]
Create, review and accept Commit guidelines

**Comment by atamankina** [comment]
[commit_guidelines.txt](https://github.com/SNDjango/server/files/1030342/commit_guidelines.txt)

**Comment by ericaivarsson** [comment]
Es sieht gut aus, es ist gut erklärt. Wo genau wollen wir diesem Datei speichern? In unsere wiki? Vielleicht können wir da einen "Ways of Working" segment einbauen?
