### ISSUE TITLE
Implement database model

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#35]
As a developer, I want to have a database model so that I can use them for implementing system features.

![database_diagram](https://cloud.githubusercontent.com/assets/28013464/26572177/44022fa2-4519-11e7-852c-6250c02a30ec.png)

**Comment by henryk3dp** [comment]
maybe UserPicture should be integrated in User, as it's a 1:1 relation.

**Comment by uttamdhakal** [comment]
and why do we need id in every model when django does that automatically?

**Comment by atamankina** [comment]
We can integrate UserPicture in User if we don't want to scale it up later to saving profile picture history.

**Comment by atamankina** [comment]
@uttamdhakal the diagram shows what we should see as the result in the database, it doesn't show how it is implemented.

**Comment by atamankina** [comment]
Reviewed, change request added.

**Comment by atamankina** [comment]
Verified with Google Chrome on Windows 8.1, devel branch, latest commit 14177fa.

Issues:
- all fields required for user https://github.com/SNDjango/server/issues/87
- no connection between registered user and user model in these schema https://github.com/SNDjango/server/issues/88
