### ISSUE TITLE
Click Sign Out button

### ISSUE THREAD

**Issue by tatankayotanka** [SNDjango/server#4]
As a logged in user, I want to log out by clicking on the Sign Out button on each page
Acceptance criteria
1. User is logged in, clicking on Sign Out button on the navbar
2. After clicking, user is redirected to the main view logged out page (See Spec--Main view logged out)

**Comment by ericaivarsson** [comment]
Is complying with acceptance criteria, will move to QA. (it does not redirect to login page but the main page which is good)

**Comment by atamankina** [comment]
Fixed AC. Verified with Firefox 53.0.3 on Windows 8.1 on devel branch with latest commit e82ae04.
