### ISSUE TITLE
Change user password

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#46]
As a user, I want to be able to change my password, so that I can meet the security requirements.

Acceptance Criteria:
- User profile page has Change Password button
- Clicking the Change Password button redirects to the Change Password page
- The Change password page shows the following input fields: old password, new password
- The Change password page shows the following buttons: Save and Cancel
- Clicking Cancel redirects to user profile page without making any changes
- The Save button page updates the user password and redirects to login page

Error cases:
- old password invalid: show corresponding error message
- new password invalid (wrong format): show corresponding error message

**Comment by henryk3dp** [comment]
django automatically logs the user out on password change. I wouldn't want to change that for security reasons. 
Also adding a new password confirmation field makes sense to prevent locking the user out if they make a typo.

**Comment by tatankayotanka** [comment]
Problem： Cancel redirects to index now. I can make this change locally, but can't push to our repo.

**Comment by tatankayotanka** [comment]
@Teszko Can you make this small change, after cancel redirect to url profile
