### ISSUE TITLE
Edit user profile

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#48]
As a user, I want to be able to change my profile information so that I keep it up to date.
Acceptance Criteria:
- My Profile page has the Edit button
- Clicking the Edit button shows the Profile page in editing mode (without the Edit button and with input fields pre-filled with current user information)
- All fields except login name and email are editable
- Page in editing mode has Save and Cancel buttons
- Cancel button redirects to user profile page in the state before clicking Edit
- Save button saves the edited profile information
- After saving the information the user is redirected to user profile page, the edited fields are updated accordingly and the success message is displayed on top of the page

**Comment by tatankayotanka** [comment]
Save process： 
1. Edit button on buttom and clickable
2. After clicking, redirected to edit mode with input fields for each attributes
3. Inputs for some fields 
4. Click on save, redirected to myprofile page with updated information

Cancel:
1. Edit age
2. Click on cancel
3. Redirected to myprofile and the input field was not recorded as cancel was clicked 


Problem:
upload profile pic seems to have worked, but there is another ticket for the profiel pic.

**Comment by tatankayotanka** [comment]
I will give a pass to this ticket, as no profile pic is mentioned.

**Comment by atamankina** [comment]
Editing layout should be improved, it is also unresponsive currently.
Bug: no way to add/edit first name and last name.
Verified with google chrome latest on Windows 10, commit  00695fb.

**Comment by atamankina** [comment]
Usability issues: 
- fields have different order on the edit profile page and on the profile page
- skype contact is usually not a URL
- expected URL format can be specified
