### ISSUE TITLE
Implement MyPosts

### ISSUE THREAD

**Issue by tatankayotanka** [SNDjango/server#50]
As a user, I want to view my posts on a separate page so that I always have an overview of what I posted

Acceptance Criteria:
- My posts are displayed on my posts page
- My posts are not displayed for other users on my posts page
- I don't see posts from other users on my post page
- The most recent posts shown first

**Comment by tatankayotanka** [comment]
@BenKet 
I have seen a commit of yours that implemented the funtion view my posts by clicking on My Posts. As there is no ticket on the board, I created this simple one so that everybody knows this has been implemented. I just did redundant implementation. Please create ticket on the board and update your progress so that others can see where we are right now on the project.

**Comment by atamankina** [comment]
@BenKet please, add acceptance criteria, so that I know what to test

**Comment by tatankayotanka** [comment]
@atamankina 
Lukas has done a primary implementation that replaces MyPosts with Hot. The branch has not yet been merged.

**Comment by pr0me** [comment]
nono, there are still two existing sites: Hot (main page in logged in view, as described) and MyPosts (all posts a specific user uploaded himself)

**Comment by atamankina** [comment]
Verified with Google Chrome on Windows 8.1, devel branch, latest commit 4098113 .
