### ISSUE TITLE
Improve redirect after upload

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#64]
Consider having the following buttons:
- Upload and go to main
- Upload and add another
- Cancel and got to main

**Comment by uttamdhakal** [comment]
Maybe after uploading it's better redirecting to myPost instead of main?

**Comment by uttamdhakal** [comment]
and is "Upload and add another" really important?

**Comment by tatankayotanka** [comment]
@uttamdhakal  I don't think upload and add another is really that important here. 
Cancel is added, redirection to main is correct.
