### ISSUE TITLE
Responsive images

### ISSUE THREAD

**Issue by ericaivarsson** [SNDjango/server#72]
As a user, i want the images on the posts to be responsive. 

Acceptance criteria: 
When screen size is changed, images will be adjusted accordingly. 

-> use bootstramp responsive images?

**Comment by ericaivarsson** [comment]
@pr0me  can we use the same solution for the logo on navbar?

**Comment by ericaivarsson** [comment]
@pr0me I would like to review this but I can´t find which branch you have used for your development?

**Comment by atamankina** [comment]
Verified with google chrome latest on Windows 10, commit  00695fb.
