### ISSUE TITLE
Add Hot menu item on navbar logged in

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#79]
I would suggest to add the "Hot" or "Trending" or whatever menu item near the logo to the Navbar logged in to improve usability and provide easy navigation to that page from other pages: we are adding additional meaning to that page as "showing hot content" and the action "Click the logo to go to the Hot page" is not clear for a user (as a user, I would get lost on the website). Logo should also redirect to that page as to main.

**Comment by tatankayotanka** [comment]
1. Hot menu added to the navbar beside logo
2. Active clicked on 
3. Redirection as logo to main.

Summary: requirements are met.
