### ISSUE TITLE
Main view (not logged in)

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#8]
As a user, I want to see the intro page so that I see what the site is about

Acceptance Criteria:
- The page contains description of our web-site and its functions
- The text contains engagement to sign in or sign up
- The page has navbar logged out which is implemented in another story

Implementation questions:
- Maybe the page can contain some demo content

**Comment by ericaivarsson** [comment]
In class, Tim said that people can decide when they publish a picture if it should be public or private. Doesn´t this mean that we can have a "hot" page active with all the pictures that people put as public? Then the main site doesn´t only have to contain "information about us"...

**Comment by atamankina** [comment]
Design and ideas needed.

**Comment by atamankina** [comment]
Good for now.
Verified with Google Chrome on Windows 8.1, devel branch, latest commit 4098113 .
