### ISSUE TITLE
Redesign Content item buttons

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#80]
I would suggest the following redesign for buttons under the picture:
- Each button should have Glyph icon + Text in it: Like icon+"Like it!", Comment icon + "Comment it", Share icon + "Share it", Star icon + "Collect it" for adding to favorites (text can be without "it")
- Add to favorites button is typically yellow
- Consider making button width equal like here https://www.w3schools.com/bootstrap/tryit.asp?filename=trybs_button_group_justified&stacked=h

**Comment by tatankayotanka** [comment]
I think it is also a good ideas to show the number of likes near the Like icon.

**Comment by atamankina** [comment]
Verified with google chrome latest on Windows 10, commit 00695fb.

**Comment by atamankina** [comment]
Issue with iPhone 5: the text on the Comment button is cut off.
