### ISSUE TITLE
Make logo icon responsive

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#83]
On smaller screens logo looks monstrous, we should make it responsive.

![01-jun-17 18-49-34](https://cloud.githubusercontent.com/assets/28013464/26691211/93f2c492-46fc-11e7-8f3c-c0f3e9ff954f.png)

**Comment by ericaivarsson** [comment]
I´ll try to take care of this one tomorrow. Shouldnt be too difficult with bootstrap images.

**Comment by ericaivarsson** [comment]
I think otherwise it´s possible to use % instead of fix pixels. I´ll look into it.

**Comment by atamankina** [comment]
Logo changed and the issue is not present anymore

**Comment by ericaivarsson** [comment]
Great!!!
