### ISSUE TITLE
All fields required for User Entity

### ISSUE THREAD

**Issue by atamankina** [SNDjango/server#87]
All fields for User entity are required which is unwanted behavior. In the Visio diagram the required fields are marked in bold for the User entity: login_name, email, password.
This results in inability to create a User without filling in all fields.

![01-jun-17 20-12-43](https://cloud.githubusercontent.com/assets/28013464/26694121/b47ce058-4706-11e7-8b6e-52d10e40203b.png)

**Comment by tatankayotanka** [comment]
Now only username and password are required.

**Comment by atamankina** [comment]
Verified with google chrome latest on Windows 10, commit  00695fb.
