### ISSUE TITLE
add search on navbar (logged-in)

### ISSUE THREAD

**Issue by tatankayotanka** [SNDjango/server#89]
As a user, I want to see a search area and button on the navbar after I log in.

AC:
1. Search consists of two components:
 an input field to get text input from user on the left
 a search button, either a normal button or a magnifier glyphicon   on the right of the input field

2. Input field and button are well aligned horizontally

3. Placeholder for the input field exists to remind the user to inpu text, such as "Search for memes here"

4. The whole search area is in the middle part of the navbar

5. Responsive

**Comment by pr0me** [comment]
i would suggest a dedicated search page. In-navbar search field is unnecessary imho and popup search complicated for the mobile view.

**Comment by atamankina** [comment]
Looks cool.
Verified with google chrome latest on Windows 10, commit 00695fb.

**Comment by atamankina** [comment]
Issue on small screens: when tapping the search button, the hamburger menu is not dismissed and overlaps the search view
